### ISSUE TITLE
fix upload credentials

### ISSUE THREAD

**Issue by headupinclouds** [hunter-packages/ogles_gpgpu#31]
> Simple request fails. Check your password.
> The command "./hunter/maintenance/upload-cache-to-github.py --username ingenue --repo-owner ingenue --repo hunter-cache --cache-dir ${HOME}/.hunter/_Base/Cache --temp-dir ${HOME}/__TEMP_HUNTER

@ruslo: https://travis-ci.org/hunter-packages/ogles_gpgpu/jobs/310954571#L3440

**Comment by ruslo** [comment]
https://github.com/hunter-packages/ogles_gpgpu/pull/30
