### ISSUE TITLE
Cmake error

### ISSUE THREAD

**Issue by binaryroot** [hunter-packages/ogles_gpgpu#37]
Hello,
Could you please help me with compiling app for android platform. I have the following error during perform build-android.sh.

sudo /Users/nazariii/Development/gl/ogles_gpgpu-hunter-2/bin/build-android.sh Python version: 3.6 Build dir: /_builds/android-ndk-r10e-api-19-armeabi-v7a-neon-Release Execute command: [whichcmake`
]

[/]> "which" "cmake"

/usr/local/bin/cmake
Execute command: [
cmake
--version
]

[/]> "cmake" "--version"

cmake version 3.9.6

CMake suite maintained and supported by Kitware (kitware.com/cmake).
Execute command: [
cmake
-H.
-B/_builds/android-ndk-r10e-api-19-armeabi-v7a-neon-Release
-DCMAKE_BUILD_TYPE=Release
-GUnix Makefiles
-DCMAKE_TOOLCHAIN_FILE=/Users/nazariii/Development/gl/polly-master/android-ndk-r10e-api-19-armeabi-v7a-neon.cmake
-DCMAKE_VERBOSE_MAKEFILE=ON
-DPOLLY_STATUS_DEBUG=ON
-DHUNTER_STATUS_DEBUG=ON
-DOGLES_GPGPU_BUILD_TESTS=ON
-DOGLES_GPGPU_OPENGL_ES3=OFF
-DHUNTER_CONFIGURATION_TYPES=Release
-DGAUZE_ANDROID_USE_EMULATOR=YES
]

[/]> "cmake" "-H." "-B/_builds/android-ndk-r10e-api-19-armeabi-v7a-neon-Release" "-DCMAKE_BUILD_TYPE=Release" "-GUnix Makefiles" "-DCMAKE_TOOLCHAIN_FILE=/Users/nazariii/Development/gl/polly-master/android-ndk-r10e-api-19-armeabi-v7a-neon.cmake" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DPOLLY_STATUS_DEBUG=ON" "-DHUNTER_STATUS_DEBUG=ON" "-DOGLES_GPGPU_BUILD_TESTS=ON" "-DOGLES_GPGPU_OPENGL_ES3=OFF" "-DHUNTER_CONFIGURATION_TYPES=Release" "-DGAUZE_ANDROID_USE_EMULATOR=YES"

CMake Error: The source directory "/" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
Command exit with status "1": [/]> "cmake" "-H." "-B/_builds/android-ndk-r10e-api-19-armeabi-v7a-neon-Release" "-DCMAKE_BUILD_TYPE=Release" "-GUnix Makefiles" "-DCMAKE_TOOLCHAIN_FILE=/Users/nazariii/Development/gl/polly-master/android-ndk-r10e-api-19-armeabi-v7a-neon.cmake" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DPOLLY_STATUS_DEBUG=ON" "-DHUNTER_STATUS_DEBUG=ON" "-DOGLES_GPGPU_BUILD_TESTS=ON" "-DOGLES_GPGPU_OPENGL_ES3=OFF" "-DHUNTER_CONFIGURATION_TYPES=Release" "-DGAUZE_ANDROID_USE_EMULATOR=YES"

Log: /_logs/polly/android-ndk-r10e-api-19-armeabi-v7a-neon/log.txt
*** FAILED ***
`

**Comment by headupinclouds** [comment]
Here is the command you are running:

```
sudo /Users/nazariii/Development/gl/ogles_gpgpu-hunter-2/bin/build-android.sh 
```

I would drop the `sudo` and execute the command from the project directory:

```
cd ogles_gpgpu-hunter-2 # in your case
./bin/build-android.sh
```

This ends up producing the following build command:
```
Execute command: [
cmake
-H.
-B/_builds/android-ndk-r10e-api-19-armeabi-v7a-neon-Release
-DCMAKE_BUILD_TYPE=Release
-GUnix Makefiles
-DCMAKE_TOOLCHAIN_FILE=/Users/nazariii/Development/gl/polly-master/android-ndk-r10e-api-19-armeabi-v7a-neon.cmake
-DCMAKE_VERBOSE_MAKEFILE=ON
-DPOLLY_STATUS_DEBUG=ON
-DHUNTER_STATUS_DEBUG=ON
-DOGLES_GPGPU_BUILD_TESTS=ON
-DOGLES_GPGPU_OPENGL_ES3=OFF
-DHUNTER_CONFIGURATION_TYPES=Release
-DGAUZE_ANDROID_USE_EMULATOR=YES
]
```

Note that `-H.` will treat your *current* working directory as the project directory, and `-B/_builds/...` will try to produce a build directory in your root (which is probably why you were adding `sudo`).  If you run the command from the ogles_gpgpu directory, then it should work.  This will produce a *library* that you can include in another project.
