### ISSUE TITLE
Android library path

### ISSUE THREAD

**Issue by binaryroot** [hunter-packages/ogles_gpgpu#38]
Hello, 

I have compiled successfully library via `./bin/build-android.sh` and file `test-ogles_gpgpu` was copied to the emulator. However,  I am able to find '.so' library which I might use in my project. As I understand right it should be file with name 'og_jni_wrapper.so'. 

[log.txt](https://github.com/hunter-packages/ogles_gpgpu/files/1693431/log.txt)

Could you please clarify how I can find library output file after compilation?

Thank you for your library and support.

**Comment by headupinclouds** [comment]
You need run the install commands.  You can do this by adding `--install` to the sample `build-android.sh` script you have been using:

```
polly.py --toolchain ${TOOLCHAIN} --verbose  <SNIP> --test --fwd ${ARGS[@]} --test --install
```

**Comment by binaryroot** [comment]
Thank you for your responses.

Just for double check, I have tried to run as you wrote. For now I am able to see '_install' folder where I found 'libogles_gpgpu.a' file. So this this library which I might use in my project for eyes recognition. Right? Also file tree on the emulator look as on the screenshot. It ok?

<img width="399" alt="screen shot 2018-02-05 at 19 14 52" src="https://user-images.githubusercontent.com/2399250/35823871-e6809908-0aa8-11e8-8a2e-095d34f78e6c.png">

**Comment by headupinclouds** [comment]
> Just for double check, I have tried to run as you wrote. For now I am able to see '_install' folder where I found 'libogles_gpgpu.a' file. So this this library which I might use in my project for eyes recognition. 

That is a static build of this ogles_gpgpu fork.  It is a generic OpenGL ES 2.0 shader framework library -- kind of like GPUImage for C++.  You can chain together the available filters to accomplish various things, but it doesn't have any kind of high level recognition capability.
